### ISSUE TITLE
crashes on config:export:content:type :(

### ISSUE THREAD

**Issue by nahueldotme** [hechoendrupal/DrupalConsole#2869]
When I run a: `drupal config:export:content:type` I'm getting:

```
Error: Call to a member function discoverModules() on null in /www/vendor/drupal/console/src/Command/Shared/ModuleTrait.php on line 26
#0 /www/vendor/drupal/console/src/Command/Config/ExportContentTypeCommand.php(83): Drupal\Console\Command\Config\ExportContentTypeCommand->moduleQuestion(Object(Drupal\Console\Style\DrupalStyle))
#1 phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php(244): Drupal\Console\Command\Config\ExportContentTypeCommand->interact(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(863): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Config\ExportContentTypeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /www/vendor/drupal/console-core/src/ConsoleApplication.php(85): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /www/vendor/drupal/console/src/Application.php(40): Drupal\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(123): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /www/vendor/drupal/console/bin/drupal.php(77): Symfony\Component\Console\Application->run()
#8 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(32): include_once('/www/vend...')
#9 phar:///usr/local/bin/drupal/bin/drupal.php(64): Drupal\Console\Utils\Launcher->launch('/www/vend...')
#10 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#11 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#12 {main}
Error: Call to a member function discoverModules() on null in Drupal\Console\Command\Config\ExportContentTypeCommand->moduleQuestion() (line 26 of /www/vendor/drupal/console/src/Command/Shared/ModuleTrait.php).```

Any ideas please?

**Comment by enzolutions** [comment]
Thanks @nahueldotme fixed in PR https://github.com/hechoendrupal/DrupalConsole/pull/2870
